In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
loans_2007=pd.read_csv('D:/pydata/LoanStats3a.csv',skiprows=1)
#清除不必要的列
half_count=len(loans_2007)/2
loans_2007=loans_2007.dropna(thresh=half_count,axis=1)
loans_2007=loans_2007.drop(['desc','url'],axis=1)
loans_2007.to_csv('D:/pydata/loans_2007.csv',index=False)

In [2]:
loans_2007=pd.read_csv('D:/pydata/loans_2007.csv')

In [3]:
loans_2007.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens
0,1077501,1296599.0,5000.0,5000.0,4975.0,36 months,10.65%,162.87,B,B2,...,171.62,Nov-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
1,1077430,1314167.0,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,...,119.66,Oct-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
2,1077175,1313524.0,2400.0,2400.0,2400.0,36 months,15.96%,84.33,C,C5,...,649.91,Nov-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
3,1076863,1277178.0,10000.0,10000.0,10000.0,36 months,13.49%,339.31,C,C1,...,357.48,Apr-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
4,1075358,1311748.0,3000.0,3000.0,3000.0,60 months,12.69%,67.79,B,B5,...,67.79,Nov-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0

In [4]:
#清除无用数据
loans_2007=loans_2007.drop(['id','member_id','funded_amnt','funded_amnt_inv','grade','sub_grade','emp_title','issue_d'],axis=1)
loans_2007 = loans_2007.drop(['zip_code', 'out_prncp', 'out_prncp_inv', 'total_pymnt','total_pymnt_inv', 'total_rec_prncp'], axis=1)
loans_2007 = loans_2007.drop(['total_rec_int', 'total_rec_late_fee','recoveries', 'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt'], axis=1)

In [5]:
print(loans_2007.iloc[0])
print(loans_2007.shape[1])

loan_amnt                            5000
term                            36 months
int_rate                           10.65%
installment                        162.87
emp_length                      10+ years
home_ownership                       RENT
annual_inc                          24000
verification_status              Verified
loan_status                    Fully Paid
pymnt_plan                              n
purpose                       credit_card
title                            Computer
addr_state                             AZ
dti                                 27.65
delinq_2yrs                             0
earliest_cr_line                 Jan-1985
inq_last_6mths                          1
open_acc                                3
pub_rec                                 0
revol_bal                           13648
revol_util                          83.7%
total_acc                               9
initial_list_status                     f
last_credit_pull_d               Nov-2016
collections_12_mths_ex_med              0
policy_code                             1
application_type               INDIVIDUAL
acc_now_delinq                          0
chargeoff_within_12_mths                0
delinq_amnt                             0
pub_rec_bankruptcies                    0
tax_liens                               0
Name: 0, dtype: object
32

In [6]:
print(loans_2007['loan_status'].value_counts())

Fully Paid                                             33902
Charged Off                                             5658
Does not meet the credit policy. Status:Fully Paid      1988
Does not meet the credit policy. Status:Charged Off      761
Current                                                  201
Late (31-120 days)                                        10
In Grace Period                                            9
Late (16-30 days)                                          5
Default                                                    1
Name: loan_status, dtype: int64

In [7]:
loans_2007=loans_2007[(loans_2007['loan_status']=='Fully Paid') | (loans_2007['loan_status']=='Charged Off')]

status_replace={
    'loan_status':{
        'Fully Paid':1,
        'Charged Off':0,
    }
}
loans_2007=loans_2007.replace(status_replace)

In [8]:
loans_2007.head()

,loan_amnt,term,int_rate,installment,emp_length,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,initial_list_status,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens
0,5000.0,36 months,10.65%,162.87,10+ years,RENT,24000.0,Verified,1,n,...,f,Nov-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
1,2500.0,60 months,15.27%,59.83,< 1 year,RENT,30000.0,Source Verified,0,n,...,f,Oct-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
2,2400.0,36 months,15.96%,84.33,10+ years,RENT,12252.0,Not Verified,1,n,...,f,Nov-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
3,10000.0,36 months,13.49%,339.31,10+ years,RENT,49200.0,Source Verified,1,n,...,f,Apr-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
5,5000.0,36 months,7.90%,156.46,3 years,RENT,36000.0,Source Verified,1,n,...,f,Jan-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0

In [9]:
#去除空数据
orig_columns=loans_2007.columns
drop_columns=[]
for col in orig_columns:
    col_series=loans_2007[col].dropna().unique( )
    if len(col_series)==1:
        drop_columns.append(col)
loans_2007=loans_2007.drop(drop_columns,axis=1)

In [10]:
loans_2007.to_csv('D:/pydata/filtered_loans_2007.csv',index=False)

In [11]:
#统计缺失值
loans=pd.read_csv('D:/pydata/filtered_loans_2007.csv')
null_counts=loans.isnull().sum()

In [12]:
null_counts

loan_amnt                  0
term                       0
int_rate                   0
installment                0
emp_length              1073
home_ownership             0
annual_inc                 0
verification_status        0
loan_status                0
pymnt_plan                 0
purpose                    0
title                     11
addr_state                 0
dti                        0
delinq_2yrs                0
earliest_cr_line           0
inq_last_6mths             0
open_acc                   0
pub_rec                    0
revol_bal                  0
revol_util                50
total_acc                  0
last_credit_pull_d         2
pub_rec_bankruptcies     697
dtype: int64

In [13]:
#去掉缺失值较多的数据
loans=loans.drop('pub_rec_bankruptcies',axis=1)
loans=loans.dropna(axis=0)

In [14]:
loans.dtypes.value_counts()

object     12
float64    10
int64       1
dtype: int64

In [15]:
#对object数据进行格式转换
mapping_dict={
    'emp_length':{
        '10+ years':10,
        '9 years':9,
        '8 years':8,
        '7 years':7,
        '6 years':6,
        '5 years':5,
        '4 years':4,
        '3 years':3,
        '2 years':2,
        '1 year':1,
        'n/a':0
    }
}
loans=loans.drop(['last_credit_pull_d','earliest_cr_line','addr_state','title'],axis=1)
loans['int_rate']=loans['int_rate'].str.rstrip('%').astype('float')
loans['revol_util']=loans['revol_util'].str.rstrip('%').astype('float')
loans=loans.replace(mapping_dict)

In [16]:
cat_columns=['home_ownership','verification_status','emp_length','purpose','term']
dummy_df=pd.get_dummies(loans[cat_columns])
loans=pd.concat([loans,dummy_df],axis=1)
loans=loans.drop(cat_columns,axis=1)
loans=loans.drop('pymnt_plan',axis=1)

loans.to_csv('D:/pydata/cleaned_loans2007.csv',index=False)

In [17]:
loans=pd.read_csv('D:/pydata/cleaned_loans2007.csv')

In [18]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38428 entries, 0 to 38427
Data columns (total 48 columns):
loan_amnt                              38428 non-null float64
int_rate                               38428 non-null float64
installment                            38428 non-null float64
annual_inc                             38428 non-null float64
loan_status                            38428 non-null int64
dti                                    38428 non-null float64
delinq_2yrs                            38428 non-null float64
inq_last_6mths                         38428 non-null float64
open_acc                               38428 non-null float64
pub_rec                                38428 non-null float64
revol_bal                              38428 non-null float64
revol_util                             38428 non-null float64
total_acc                              38428 non-null float64
home_ownership_MORTGAGE                38428 non-null int64
home_ownership_NONE                    38428 non-null int64
home_ownership_OTHER                   38428 non-null int64
home_ownership_OWN                     38428 non-null int64
home_ownership_RENT                    38428 non-null int64
verification_status_Not Verified       38428 non-null int64
verification_status_Source Verified    38428 non-null int64
verification_status_Verified           38428 non-null int64
emp_length_1                           38428 non-null int64
emp_length_2                           38428 non-null int64
emp_length_3                           38428 non-null int64
emp_length_4                           38428 non-null int64
emp_length_5                           38428 non-null int64
emp_length_6                           38428 non-null int64
emp_length_7                           38428 non-null int64
emp_length_8                           38428 non-null int64
emp_length_9                           38428 non-null int64
emp_length_10                          38428 non-null int64
emp_length_< 1 year                    38428 non-null int64
purpose_car                            38428 non-null int64
purpose_credit_card                    38428 non-null int64
purpose_debt_consolidation             38428 non-null int64
purpose_educational                    38428 non-null int64
purpose_home_improvement               38428 non-null int64
purpose_house                          38428 non-null int64
purpose_major_purchase                 38428 non-null int64
purpose_medical                        38428 non-null int64
purpose_moving                         38428 non-null int64
purpose_other                          38428 non-null int64
purpose_renewable_energy               38428 non-null int64
purpose_small_business                 38428 non-null int64
purpose_vacation                       38428 non-null int64
purpose_wedding                        38428 non-null int64
term_ 36 months                        38428 non-null int64
term_ 60 months                        38428 non-null int64
dtypes: float64(12), int64(36)
memory usage: 14.1 MB

In [19]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
cols = loans.columns
train_cols = cols.drop('loan_status')
#得到特征
features = loans[train_cols]
#得到标签
target = loans['loan_status']
lr.fit(features, target)
predictions = lr.predict(features)

In [20]:
#第一次测试——使用逻辑回归测试
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict,KFold
lr = LogisticRegression()
kf = KFold()
predictions = cross_val_predict(lr, features, target, cv=kf)
predictions = pd.Series(predictions)

#定义指标
#True positives 
tp_filter = (predictions == 1) & (loans['loan_status']== 1) 
tp = len(predictions[tp_filter])
#False positives
fp_filter = (predictions == 1) & (loans['loan_status']== 0) 
fp = len(predictions[fp_filter])
#True negatives 
tn_filter = (predictions == 0) & (loans['loan_status']== 0) 
tn = len(predictions[tn_filter])
#False negatives 
fn_filter = (predictions == 0) & (loans['loan_status'] == 1) 
fn = len(predictions[fn_filter])
# Rates
tpr = tp / float((tp + fn))
fpr = fp / float((fp + tn))

print(tpr)
print(fpr)

0.9991519520247145
0.997967104047311

In [22]:
#第二次测试——添加权重项，平衡数据的权重和
lr=LogisticRegression(class_weight='balanced')
kf=KFold()
predictions=cross_val_predict(lr,features,target,cv=kf)
predictions=pd.Series(predictions)

#True positives 
tp_filter = (predictions == 1) & (loans['loan_status']== 1) 
tp = len(predictions[tp_filter])
#False positives
fp_filter = (predictions == 1) & (loans['loan_status']== 0) 
fp = len(predictions[fp_filter])
#True negatives 
tn_filter = (predictions == 0) & (loans['loan_status']== 0) 
tn = len(predictions[tn_filter])
#False negatives 
fn_filter = (predictions == 0) & (loans['loan_status'] == 1) 
fn = len(predictions[fn_filter])
# Rates
tpr = tp / float((tp + fn))
fpr = fp / float((fp + tn))

print(tpr)
print(fpr)

0.6699881879032014
0.3975235631121789

In [23]:
#第三次测试——自定义权重项
penalty={
    0:5,
    1:1
}
lr=LogisticRegression(class_weight=penalty)
kf=KFold()
predictions=cross_val_predict(lr,features,target,cv=kf)
predictions=pd.Series(predictions)

#True positives 
tp_filter = (predictions == 1) & (loans['loan_status']== 1) 
tp = len(predictions[tp_filter])
#False positives
fp_filter = (predictions == 1) & (loans['loan_status']== 0) 
fp = len(predictions[fp_filter])
#True negatives 
tn_filter = (predictions == 0) & (loans['loan_status']== 0) 
tn = len(predictions[tn_filter])
#False negatives 
fn_filter = (predictions == 0) & (loans['loan_status'] == 1) 
fn = len(predictions[fn_filter])
# Rates
tpr = tp / float((tp + fn))
fpr = fp / float((fp + tn))

print(tpr)
print(fpr)

0.7197201441681558
0.4681204952873776

In [24]:
#第四次测试——随机森林
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=10,class_weight='balanced',random_state=1)
kf=KFold()
predictions=cross_val_predict(lr,features,target,cv=kf)
predictions=pd.Series(predictions)

#True positives 
tp_filter = (predictions == 1) & (loans['loan_status']== 1) 
tp = len(predictions[tp_filter])
#False positives
fp_filter = (predictions == 1) & (loans['loan_status']== 0) 
fp = len(predictions[fp_filter])
#True negatives 
tn_filter = (predictions == 0) & (loans['loan_status']== 0) 
tn = len(predictions[tn_filter])
#False negatives 
fn_filter = (predictions == 0) & (loans['loan_status'] == 1) 
fn = len(predictions[fn_filter])
# Rates
tpr = tp / float((tp + fn))
fpr = fp / float((fp + tn))

print(tpr)
print(fpr)

0.7197201441681558
0.4681204952873776

In [ ]:
# 模型效果不理想时，可以考虑的调整策略：
# 1.调节正负样本的权重参数;
# 2.更换模型算法;
# 3.同时几个使用模型进行预测，然后取去测的最终结果;
# 4.使用原数据，生成新特征;
# 5.调整模型参数.